---
- name: Copy the SNMP Exporter systemd service file
  template:
    src: snmp_exporter.service.j2
    dest: /lib/systemd/system/snmp_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart snmp exporter

- name: Copy configuration file
  template:
    src: snmp.yml.j2
    dest: /etc/snmp_exporter/snmp.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - reload snmp exporter
